In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [8]:
source= requests.get('https://en.wikipedia.org/wiki/List_of_districts_in_the_London_Borough_of_Redbridge').text
soup= BeautifulSoup(source,'lxml')
liste= soup.find('ul')
#print(liste.prettify())

In [7]:
redbridge_neigh=[]
for li in liste.find_all('li'):
    try:
        neigh= li.a.text
    except:
        neigh= li.text
    redbridge_neigh.append(neigh)
redbridge_neigh

['Aldborough Hatch',
 'Aldersbrook',
 'Barkingside',
 'Chadwell Heath',
 'Clayhall',
 'Cranbrook',
 'Fairlop',
 'Fullwell Cross',
 'Gants Hill',
 'Goodmayes',
 'Hainault',
 'Ilford',
 'Little Heath',
 'Loxford',
 'Mayfield',
 'Monkhams',
 'Newbury Park',
 'Redbridge',
 'Seven Kings',
 'Snaresbrook',
 'South Woodford',
 'Valentines',
 'Wanstead',
 'Wanstead Flats',
 'Woodford',
 'Woodford Bridge',
 'Woodford Green']

In [9]:
redbridge_neigh_df= pd.DataFrame(columns=['Neighborhood','Latitude','Longitude'])
redbridge_neigh_df

Empty DataFrame
Columns: [Neighborhood, Latitude, Longitude]
Index: []

In [12]:
import googlemaps
API_key= 'AIzaSyAaZ45aH6Iuhjkx8reDnDDZ1qQ5Cs61h2g'
gmaps= googlemaps.Client(key= API_key)

In [15]:
num_of_neigh= len(redbridge_neigh)
for i in range(0, num_of_neigh):
    neigh= redbridge_neigh[i]
    redbridge_neigh_df.loc[i, 'Neighborhood']= neigh
    results= gmaps.geocode(neigh+', redbridge, london')
    try:
        lat= results[0]['geometry']['location']['lat']
        lon= results[0]['geometry']['location']['lng']
    except:
        lat= 'None'
        lon= 'None'
    redbridge_neigh_df.loc[i, 'Latitude']= lat
    redbridge_neigh_df.loc[i, 'Longitude']= lon
    
        
    
redbridge_neigh_df

        Neighborhood Latitude  Longitude
0   Aldborough Hatch  51.5855   0.098766
1        Aldersbrook  51.5515  0.0488415
2        Barkingside  51.5899  0.0838742
3     Chadwell Heath  51.5722   0.141995
4           Clayhall   51.587  0.0687735
5          Cranbrook  51.5613  0.0687103
6            Fairlop  51.6019  0.0842012
7     Fullwell Cross  51.5945    0.08572
8         Gants Hill  51.5768  0.0661732
9          Goodmayes  51.5662   0.110297
10          Hainault  51.6083   0.119312
11            Ilford  51.5566   0.076251
12      Little Heath  51.5832   0.120603
13           Loxford  51.5487   0.079912
14          Mayfield  51.5643   0.120937
15          Monkhams  51.6029  0.0272124
16      Newbury Park  51.5735  0.0889767
17         Redbridge  51.5748  0.0507539
18       Seven Kings  51.5636   0.098511
19       Snaresbrook  51.5857  0.0084531
20    South Woodford  51.5913  0.0264721
21        Valentines  51.5654  0.0709168
22          Wanstead  51.5768  0.0249881
23    Wanstead Flats  51.5589   0.036322
24          Woodford  51.6042  0.0325025
25   Woodford Bridge  51.6057  0.0544589
26    Woodford Green  51.6093  0.0405521